#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-7fd_o8bi'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-7fd_o8bi/exec:/tmp/rboxc-tar-original-7fd_o8bi/deps' 203 ${1+"$@"}
exit 1
