#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-fhj_6q4w'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-fhj_6q4w/exec:/tmp/rboxc-tar-original-fhj_6q4w/deps' 204 ${1+"$@"}
exit 1
