#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-3l2_i2i0'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-3l2_i2i0/exec:/tmp/rboxc-tar-original-3l2_i2i0/deps' 187 ${1+"$@"}
exit 1
