#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-6jy4t4pf'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-6jy4t4pf/exec:/tmp/rboxc-tar-original-6jy4t4pf/deps' 88 ${1+"$@"}
exit 1
