#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-07d6hrsw'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-07d6hrsw/exec:/tmp/rboxc-tar-original-07d6hrsw/deps' 186 ${1+"$@"}
exit 1
