#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-v_9w_7uf'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-v_9w_7uf/exec:/tmp/rboxc-tar-original-v_9w_7uf/deps' 168 ${1+"$@"}
exit 1
