#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-y9yfu25u'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-y9yfu25u/exec:/tmp/rboxc-tar-original-y9yfu25u/deps' 173 ${1+"$@"}
exit 1
