#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-iq8ymq7d'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-iq8ymq7d/exec:/tmp/rboxc-tar-original-iq8ymq7d/deps' 204 ${1+"$@"}
exit 1
