#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-bgsm6_f8'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-bgsm6_f8/exec:/tmp/rboxc-tar-original-bgsm6_f8/deps' 163 ${1+"$@"}
exit 1
