#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-ss_1_3ix'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-ss_1_3ix/exec:/tmp/rboxc-tar-original-ss_1_3ix/deps' 203 ${1+"$@"}
exit 1
