#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-5wm_emgb'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-5wm_emgb/exec:/tmp/rboxc-tar-original-5wm_emgb/deps' 197 ${1+"$@"}
exit 1
