#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-e_hpsju1'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-e_hpsju1/exec:/tmp/rboxc-tar-original-e_hpsju1/deps' 223 ${1+"$@"}
exit 1
