#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-c4q9q46n'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-c4q9q46n/exec:/tmp/rboxc-tar-original-c4q9q46n/deps' 88 ${1+"$@"}
exit 1
