#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-4_zz2xpd'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-4_zz2xpd/exec:/tmp/rboxc-tar-original-4_zz2xpd/deps' 21 ${1+"$@"}
exit 1
