#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-hnd73nfx'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-hnd73nfx/exec:/tmp/rboxc-tar-original-hnd73nfx/deps' 21 ${1+"$@"}
exit 1
