#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-_q8cf2xr'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-_q8cf2xr/exec:/tmp/rboxc-tar-original-_q8cf2xr/deps' 22 ${1+"$@"}
exit 1
