#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-sv4pmi3z'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-sv4pmi3z/exec:/tmp/rboxc-tar-original-sv4pmi3z/deps' 199 ${1+"$@"}
exit 1
