#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-dyi0q60c'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-dyi0q60c/exec:/tmp/rboxc-tar-original-dyi0q60c/deps' 92 ${1+"$@"}
exit 1
