#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-k3mm2z0g'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-k3mm2z0g/exec:/tmp/rboxc-tar-original-k3mm2z0g/deps' 185 ${1+"$@"}
exit 1
