#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-hh9fg2fq'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-hh9fg2fq/exec:/tmp/rboxc-tar-original-hh9fg2fq/deps' 153 ${1+"$@"}
exit 1
