#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-1ik6_nyj'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-1ik6_nyj/exec:/tmp/rboxc-tar-original-1ik6_nyj/deps' 46 ${1+"$@"}
exit 1
