#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-_87ak5mz'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-_87ak5mz/exec:/tmp/rboxc-tar-original-_87ak5mz/deps' 160 ${1+"$@"}
exit 1
