#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-nakv5j3n'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-nakv5j3n/exec:/tmp/rboxc-tar-original-nakv5j3n/deps' 187 ${1+"$@"}
exit 1
