#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-oe5d9jsz'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-oe5d9jsz/exec:/tmp/rboxc-tar-original-oe5d9jsz/deps' 217 ${1+"$@"}
exit 1
