#!/usr/bin/env python3
"""Compare bounded, valid cpio/mt operations and ordinary I/O errors."""
# SPDX-License-Identifier: GPL-3.0-or-later
import importlib.util
import json
import os
from pathlib import Path
import re
import stat
import shutil
import subprocess
import sys
import tempfile
from comparison_profile import ComparisonProfile, fingerprint

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT/'tests/gnu'))
spec = importlib.util.spec_from_file_location('reviewed', ROOT/'tests/gnu/reviewed-original.py')
runner = importlib.util.module_from_spec(spec); spec.loader.exec_module(runner)
profile = ComparisonProfile('cpio-behavior', oracle=ROOT/'build/gnu-cpio/src/cpio')
oracles = {n: ROOT/'build/gnu-cpio/src'/n for n in ('cpio', 'mt')}
hashes = {n: fingerprint(p) for n, p in oracles.items()}
driver_hash = fingerprint(Path(__file__))
cases = []
def case(name, command, args, data=b'', *, fixture=None, multicall=False):
    cases.append((name, command, args, data, fixture, multicall))
for command in oracles:
    for option in ('help', 'version'):
        case(command+'-'+option, command, ['--'+option])
        case(command+'-'+option+'-multicall', command, ['--'+option], multicall=True)
    case(command+'-unknown-option', command, ['--not-an-option'])
case('cpio-no-operands', 'cpio', [])
case('cpio-mode-conflict', 'cpio', ['-io'])
case('cpio-missing-input', 'cpio', ['-it', '-F', 'missing'])
case('cpio-missing-output-parent', 'cpio', ['-o', '-F', 'missing/archive'])
case('mt-no-operands', 'mt', [])
case('mt-invalid-operation', 'mt', ['--file=missing', 'not-an-operation'])
case('mt-missing-file', 'mt', ['--file=missing', 'status'])
case('mt-regular-file', 'mt', ['--file=input', 'status'])
case('mt-invalid-count', 'mt', ['--file=missing', 'fsf', 'abc'])
case('mt-extra-operands', 'mt', ['--file=missing', 'status', '1', 'extra'])
# Fixtures are always generated by the pinned GNU oracle from regular files.
# --reproducible removes host inode/device identity from archive comparisons.
FORMATS = ('bin', 'odc', 'newc', 'crc', 'tar', 'ustar', 'hpbin', 'hpodc')
def seed(work):
    (work/'input').write_bytes(bytes(range(256))*4+b'hello\n')
    (work/'empty').touch()
    (work/'dir').mkdir()
    (work/'dir/nested').write_bytes(b'nested text\n')
    for p in (work/'input',work/'empty',work/'dir/nested'):
        p.chmod(0o640); os.utime(p,(1700000000,1700000000))
    (work/'dir').chmod(0o750); os.utime(work/'dir',(1700000000,1700000000))
filelist = b'input\nempty\ndir\ndir/nested\n'
with tempfile.TemporaryDirectory(prefix='rboxc-cpio-oracle-') as directory:
    work=Path(directory);seed(work)
    for fmt in FORMATS:
        args=['--quiet','--reproducible','-o','-H',fmt]
        archived=subprocess.check_output([oracles['cpio'],*args],input=filelist,cwd=work,
            env={'LC_ALL':'C','LANGUAGE':'C','TZ':'UTC0'},umask=0o022)
        case('create-'+fmt,'cpio',args,filelist,fixture='source')
        case('list-'+fmt,'cpio',['--quiet','-it'],archived)
        case('extract-'+fmt,'cpio',['--quiet','-id','--no-preserve-owner'],archived)
        if fmt=='newc':
            case('create-file','cpio',args+['-F','archive'],filelist,fixture='source')
            case('create-null-list','cpio',args+['-0'],filelist.replace(b'\n',b'\0'),fixture='source')
            case('create-multicall','cpio',args,filelist,fixture='source',multicall=True)
            case('list-multicall','cpio',['--quiet','-it'],archived,multicall=True)
            case('extract-multicall','cpio',['--quiet','-id','--no-preserve-owner'],archived,multicall=True)
            case('extract-pattern','cpio',['--quiet','-id','--no-preserve-owner','dir/*'],archived)
            case('extract-to-stdout','cpio',['--quiet','-i','--to-stdout','input'],archived)
case('pass-copy','cpio',['--quiet','-pd','destination'],filelist,fixture='source')
results = []
for index, (name, command, args, data, fixture, multicall) in enumerate(cases):
    outcomes = {}
    for implementation in ('gnu', 'rboxc'):
        for instrument in (False, True):
            key = implementation+('-valgrind' if instrument else '')
            with tempfile.TemporaryDirectory(prefix='rboxc-cpio-') as directory:
                work = Path(directory); (work/'exec').mkdir(); (work/'files').mkdir()
                if fixture == 'source':
                    seed(work/'files')
                if name == 'mt-regular-file':
                    (work/'files/input').write_bytes(b'ordinary regular file\n')
                executable = oracles[command] if implementation == 'gnu' else profile.binary
                alias = work/'exec'/command; alias.symlink_to(executable)
                argv = [str(alias), *args]
                if multicall and implementation == 'rboxc':
                    box = work/'exec/rboxc'; box.symlink_to(executable)
                    argv = [str(box), command, *args]
                log = work/'memory.log'
                if instrument:
                    argv = ['/usr/bin/valgrind', '--leak-check=full', '--show-leak-kinds=all',
                            '--track-fds=yes', '--log-file='+str(log), *argv]
                done = subprocess.run(argv, input=data, cwd=work/'files', capture_output=True,
                                      env={'LC_ALL':'C', 'LANGUAGE':'C', 'HOME':directory, 'TZ':'UTC0'},
                                      umask=0o022, timeout=45)
                tree = {}
                for p in sorted((work/'files').rglob('*')):
                    info=p.lstat();entry={'mode':info.st_mode & 0o7777}
                    if p.is_symlink():entry.update(type='symlink',target=os.readlink(p))
                    elif p.is_file():entry.update(type='file',sha256=fingerprint(p),bytes=info.st_size)
                    elif p.is_dir():entry.update(type='directory')
                    else:raise AssertionError('unexpected fixture file type')
                    tree[str(p.relative_to(work/'files'))]=entry
                row = {'status':done.returncode, 'raw_stdout':done.stdout.hex(), 'raw_stderr':done.stderr.hex(),
                       'fixture':directory, 'stdout':done.stdout.replace(directory.encode(), b'<fixture>').hex(),
                       'stderr':done.stderr.replace(directory.encode(), b'<fixture>').hex(), 'tree':tree}
                if instrument:
                    saved = profile.logs/f'{index:03}-{key}.log'; shutil.copy2(log, saved)
                    contents = saved.read_text()
                    pids = set(re.findall(r'^==([0-9]+)==', contents, re.M))
                    assert len(pids) == 1
                    row.update(memory=runner.parse_memory_log(contents, pids.pop(), exec_only=True),
                               log=str(saved.relative_to(ROOT)), log_sha256=fingerprint(saved))
                outcomes[key] = row
    reference = outcomes['gnu']
    equivalent = all(all(row[k] == reference[k] for k in ('status','stdout','stderr','tree')) for row in outcomes.values())
    memory = outcomes['rboxc-valgrind']['memory']
    clean = memory['complete_exec_log'] and memory['errors'] == 0 and memory['non_inherited_descriptors'] == 0 and not any(
        memory['heap_bytes'].get(k, 0) for k in ('definitely lost','indirectly lost','possibly lost'))
    results.append({'name':name, 'command':command, 'arguments':args, 'input':data.hex(),
                    'pass':equivalent and clean, 'equivalent':equivalent, 'memory_clean':clean, 'outcomes':outcomes})
    assert fingerprint(Path(__file__)) == driver_hash
    assert all(fingerprint(p) == hashes[n] for n, p in oracles.items())
    report = {'scope':'Valid bounded archive creation/listing/extraction across eight GNU formats, copy-pass, filename lists, both dispatch forms, and ordinary option/I/O errors. Mt uses only missing paths or a private regular file; real tape operations are untested. Private fixture paths alone are normalized. Native Valgrind findings remain baseline observations.',
              **profile.metadata(), 'oracles':{n:{'path':str(p),'sha256':hashes[n]} for n,p in oracles.items()},
              'driver_sha256':driver_hash, 'planned_total':len(cases), 'complete':len(results)==len(cases),
              'passed':sum(r['pass'] for r in results), 'total':len(results), 'results':results}
    profile.report.write_text(json.dumps(report, indent=2)+'\n')
    print('PASS' if results[-1]['pass'] else 'OPEN', name, flush=True)
raise SystemExit(report['passed'] != report['total'])
