#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-t_8_1ssk'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-t_8_1ssk/exec:/tmp/rboxc-tar-original-t_8_1ssk/deps' 227 ${1+"$@"}
exit 1
