#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-9au4k3l6'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-9au4k3l6/exec:/tmp/rboxc-tar-original-9au4k3l6/deps' 9 ${1+"$@"}
exit 1
