#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-ay9xl0ij'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-ay9xl0ij/exec:/tmp/rboxc-tar-original-ay9xl0ij/deps' 212 ${1+"$@"}
exit 1
