#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-zfrmrrez'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-zfrmrrez/exec:/tmp/rboxc-tar-original-zfrmrrez/deps' 143 ${1+"$@"}
exit 1
