#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-0vscd7vn'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-0vscd7vn/exec:/tmp/rboxc-tar-original-0vscd7vn/deps' 192 ${1+"$@"}
exit 1
