#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-nnsc4qrr'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-nnsc4qrr/exec:/tmp/rboxc-tar-original-nnsc4qrr/deps' 174 ${1+"$@"}
exit 1
