#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-xwhlb3x_'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-xwhlb3x_/exec:/tmp/rboxc-tar-original-xwhlb3x_/deps' 147 ${1+"$@"}
exit 1
