#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-hrb86a4v'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-hrb86a4v/exec:/tmp/rboxc-tar-original-hrb86a4v/deps' 197 ${1+"$@"}
exit 1
