#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-f90f_6kf'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-f90f_6kf/exec:/tmp/rboxc-tar-original-f90f_6kf/deps' 191 ${1+"$@"}
exit 1
