#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-u_5zrsqs'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-u_5zrsqs/exec:/tmp/rboxc-tar-original-u_5zrsqs/deps' 162 ${1+"$@"}
exit 1
