#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-mwdkg_2o'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-mwdkg_2o/exec:/tmp/rboxc-tar-original-mwdkg_2o/deps' 195 ${1+"$@"}
exit 1
