#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-hob_rc4i'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-hob_rc4i/exec:/tmp/rboxc-tar-original-hob_rc4i/deps' 198 ${1+"$@"}
exit 1
