#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-26m4h1pg'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-26m4h1pg/exec:/tmp/rboxc-tar-original-26m4h1pg/deps' 157 ${1+"$@"}
exit 1
