#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-92ccz3vl'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-92ccz3vl/exec:/tmp/rboxc-tar-original-92ccz3vl/deps' 202 ${1+"$@"}
exit 1
