#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-2c7fk0ca'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-2c7fk0ca/exec:/tmp/rboxc-tar-original-2c7fk0ca/deps' 242 ${1+"$@"}
exit 1
