#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-8gius81w'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-8gius81w/exec:/tmp/rboxc-tar-original-8gius81w/deps' 168 ${1+"$@"}
exit 1
