#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-s6pnx1ud'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-s6pnx1ud/exec:/tmp/rboxc-tar-original-s6pnx1ud/deps' 244 ${1+"$@"}
exit 1
