#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-9t5t48zb'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-9t5t48zb/exec:/tmp/rboxc-tar-original-9t5t48zb/deps' 166 ${1+"$@"}
exit 1
