#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-lwr3n98m'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-lwr3n98m/exec:/tmp/rboxc-tar-original-lwr3n98m/deps' 240 ${1+"$@"}
exit 1
