#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-iq6jxq0i'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-iq6jxq0i/exec:/tmp/rboxc-tar-original-iq6jxq0i/deps' 64 ${1+"$@"}
exit 1
