#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-7xda7ou2'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-7xda7ou2/exec:/tmp/rboxc-tar-original-7xda7ou2/deps' 206 ${1+"$@"}
exit 1
