#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-er1o1ktr'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-er1o1ktr/exec:/tmp/rboxc-tar-original-er1o1ktr/deps' 178 ${1+"$@"}
exit 1
