#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-6w92l_6z'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-6w92l_6z/exec:/tmp/rboxc-tar-original-6w92l_6z/deps' 222 ${1+"$@"}
exit 1
