#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-9i8lh6iy'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-9i8lh6iy/exec:/tmp/rboxc-tar-original-9i8lh6iy/deps' 233 ${1+"$@"}
exit 1
