#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-e4q9cjdc'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-e4q9cjdc/exec:/tmp/rboxc-tar-original-e4q9cjdc/deps' 163 ${1+"$@"}
exit 1
