#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-m04tpa5z'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-m04tpa5z/exec:/tmp/rboxc-tar-original-m04tpa5z/deps' 171 ${1+"$@"}
exit 1
