#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-uiig7l0d'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-uiig7l0d/exec:/tmp/rboxc-tar-original-uiig7l0d/deps' 191 ${1+"$@"}
exit 1
