#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-e7p7u6dv'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-e7p7u6dv/exec:/tmp/rboxc-tar-original-e7p7u6dv/deps' 21 ${1+"$@"}
exit 1
