#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-0t0_f54k'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-0t0_f54k/exec:/tmp/rboxc-tar-original-0t0_f54k/deps' 169 ${1+"$@"}
exit 1
