#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-c1tcexgm'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-c1tcexgm/exec:/tmp/rboxc-tar-original-c1tcexgm/deps' 135 ${1+"$@"}
exit 1
