#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-1i4qoljn'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-1i4qoljn/exec:/tmp/rboxc-tar-original-1i4qoljn/deps' 150 ${1+"$@"}
exit 1
