#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-hx1pgp4o'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-hx1pgp4o/exec:/tmp/rboxc-tar-original-hx1pgp4o/deps' 171 ${1+"$@"}
exit 1
