#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-0mv2x7zz'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-0mv2x7zz/exec:/tmp/rboxc-tar-original-0mv2x7zz/deps' 189 ${1+"$@"}
exit 1
