#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-6fz2o6ap'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-6fz2o6ap/exec:/tmp/rboxc-tar-original-6fz2o6ap/deps' 19 ${1+"$@"}
exit 1
