#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-4pbm_9sc'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-4pbm_9sc/exec:/tmp/rboxc-tar-original-4pbm_9sc/deps' 151 ${1+"$@"}
exit 1
