#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-5y2s5_w5'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-5y2s5_w5/exec:/tmp/rboxc-tar-original-5y2s5_w5/deps' 46 ${1+"$@"}
exit 1
