#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-xqcea_h9'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-xqcea_h9/exec:/tmp/rboxc-tar-original-xqcea_h9/deps' 20 ${1+"$@"}
exit 1
