#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-jnv7in3_'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-jnv7in3_/exec:/tmp/rboxc-tar-original-jnv7in3_/deps' 11 ${1+"$@"}
exit 1
