#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-m5gxv0j_'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-m5gxv0j_/exec:/tmp/rboxc-tar-original-m5gxv0j_/deps' 94 ${1+"$@"}
exit 1
