#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-atw2a9ji'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-atw2a9ji/exec:/tmp/rboxc-tar-original-atw2a9ji/deps' 208 ${1+"$@"}
exit 1
