#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-4imhx3g_'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-4imhx3g_/exec:/tmp/rboxc-tar-original-4imhx3g_/deps' 175 ${1+"$@"}
exit 1
