#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-yup_c8uf'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-yup_c8uf/exec:/tmp/rboxc-tar-original-yup_c8uf/deps' 184 ${1+"$@"}
exit 1
