#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-rf_80lc4'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-rf_80lc4/exec:/tmp/rboxc-tar-original-rf_80lc4/deps' 170 ${1+"$@"}
exit 1
