#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-lieg3o0j'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-lieg3o0j/exec:/tmp/rboxc-tar-original-lieg3o0j/deps' 147 ${1+"$@"}
exit 1
