#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-s4d3dgme'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-s4d3dgme/exec:/tmp/rboxc-tar-original-s4d3dgme/deps' 152 ${1+"$@"}
exit 1
