#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-4z4qeq2u'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-4z4qeq2u/exec:/tmp/rboxc-tar-original-4z4qeq2u/deps' 222 ${1+"$@"}
exit 1
