#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-n8rux6c1'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-n8rux6c1/exec:/tmp/rboxc-tar-original-n8rux6c1/deps' 169 ${1+"$@"}
exit 1
