#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-x9p9k0yj'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-x9p9k0yj/exec:/tmp/rboxc-tar-original-x9p9k0yj/deps' 76 ${1+"$@"}
exit 1
