#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-xtz3ca7l'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-xtz3ca7l/exec:/tmp/rboxc-tar-original-xtz3ca7l/deps' 172 ${1+"$@"}
exit 1
