#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-z2cu7p0h'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-z2cu7p0h/exec:/tmp/rboxc-tar-original-z2cu7p0h/deps' 204 ${1+"$@"}
exit 1
