#! /bin/sh
test ${ZSH_VERSION+y} && alias -g '${1+"$@"}'='"$@"'
cd '/tmp/rboxc-tar-original-8gf5t6oz'
exec ${CONFIG_SHELL-/bin/bash} "/opt/src/tar-1.35/tests/testsuite" -v -d  AUTOTEST_PATH='/tmp/rboxc-tar-original-8gf5t6oz/exec:/tmp/rboxc-tar-original-8gf5t6oz/deps' 18 ${1+"$@"}
exit 1
